packages:
  - workflow
  - model
  - ui
  - block
  - test

catalog:
  '@platforma-sdk/block-tools': ^2.5.21
  '@platforma-sdk/model': ^1.23.0
  '@platforma-sdk/ui-vue': ^1.23.0
  '@platforma-sdk/tengo-builder': ^1.19.2
  '@platforma-sdk/workflow-tengo': ^2.16.0

  '@platforma-sdk/test': ^1.23.0
  '@milaboratories/graph-maker': ^1.1.57
  '@milaboratories/software-pframes-conv': ^2.1.18
  '@platforma-open/milaboratories.software-small-binaries': ^1.15.19

  'vue': ^3.5.13
  'vue-tsc': ^2.1.10

  'typescript': ^5.6.3
  'tsup': ~8.3.5
  'turbo': ^2.3.3

  'vite': ^5.4.11
  'vitest': ^2.1.5
  '@vitejs/plugin-vue': ^5.2.0

  '@changesets/cli': ^2.27.10
