packages:
  - workflow
  - model
  - ui
  - test
  - .

catalog:
  "@platforma-sdk/model": ^1.7.20
  "@platforma-sdk/ui-vue": ^1.7.22
  "@platforma-sdk/workflow-tengo": ^1.6.4
  "@platforma-sdk/block-tools": ^2.3.19
  "@platforma-sdk/test": ^1.5.43
  "@platforma-sdk/tengo-builder": ^1.15.13
  "@milaboratories/graph-maker": ^1.0.19
  '@milaboratories/software-pframes-conv': ^1.6.4
  '@platforma-open/milaboratories.software-small-binaries': ^1.13.1

  
  "vue": ^3.4.34
  "vue-tsc": ^2.0.29
  
  "typescript": ^5.5.4
  "tsup": ~8.1.2

  "vite": ^5.3.5
  "vitest": ^2.0.4
  "@vitejs/plugin-vue": ^5.1.0

  "@changesets/cli": ^2.27.7
