packages:
  - workflow
  - model
  - ui
  - block
  - test

catalog:
  '@platforma-sdk/block-tools': ^2.5.21
  '@platforma-sdk/model': ^1.23.0
  '@platforma-sdk/ui-vue': ^1.23.4
  "@platforma-sdk/tengo-builder": ^2.1.7
  "@platforma-sdk/workflow-tengo": ^4.7.1

  '@platforma-sdk/test': ^1.23.0
  '@milaboratories/graph-maker': ^1.1.61
  '@milaboratories/software-pframes-conv': ^2.1.18
  '@platforma-open/milaboratories.software-small-binaries': ^1.15.19

  'vue': ^3.5.13
  'vue-tsc': ^2.2.8

  'typescript': ^5.6.3
  'tsup': ~8.4.0
  'turbo': ^2.4.4

  'vite': ^6.2.2
  'vitest': ^3.0.9
  '@vitejs/plugin-vue': ^5.2.3

  '@changesets/cli': ^2.28.1
