packages:
  - workflow
  - model
  - ui
  - block
  - test

catalog:
  '@platforma-sdk/block-tools': ^2.5.14
  '@platforma-sdk/model': ^1.22.59
  '@platforma-sdk/ui-vue': ^1.22.59
  '@platforma-sdk/tengo-builder': ^1.17.7
  '@platforma-sdk/workflow-tengo': ^2.13.1

  '@platforma-sdk/test': ^1.22.60
  '@milaboratories/graph-maker': ^1.1.48
  '@milaboratories/software-pframes-conv': ^2.1.5
  '@platforma-open/milaboratories.software-small-binaries': ^1.15.6
  '@platforma-open/milaboratories.software-subread': ^1.0.0
  '@platforma-open/milaboratories.software-star': ^1.0.1
  '@platforma-open/milaboratories.star-read-mapping.genome-asset': ^1.1.4
  '@platforma-sdk/eslint-config': ^1.0.1

  'vue': ^3.5.13
  'vue-tsc': ^2.1.10

  'typescript': ^5.6.3
  'tsup': ~8.3.5
  'turbo': ^2.3.3

  'vite': ^5.4.11
  'vitest': ^2.1.5
  '@vitejs/plugin-vue': ^5.2.0

  '@changesets/cli': ^2.27.10
