packages:
  - workflow
  - model
  - ui
  - block
  - test

catalog:
  '@platforma-sdk/block-tools': ^2.6.6
  '@platforma-sdk/model': ^1.43.2
  '@platforma-sdk/ui-vue': ^1.43.2
  '@platforma-sdk/tengo-builder': ^2.1.21
  '@platforma-sdk/workflow-tengo': ^5.2.1

  '@platforma-sdk/test': ^1.43.7
  '@milaboratories/graph-maker': ^1.1.157
  '@milaboratories/software-pframes-conv': ^2.2.7
  '@platforma-open/milaboratories.software-small-binaries': ^1.15.19
  '@platforma-sdk/blocks-deps-updater': ^2.0.0

  'vue': ^3.5.13
  'vue-tsc': ^2.2.8

  'typescript': ^5.6.3
  'tsup': ~8.4.0
  'turbo': ^2.4.4

  'vite': ^6.2.2
  'vitest': ^3.0.9
  '@vitejs/plugin-vue': ^5.2.3

  '@changesets/cli': ^2.28.1
